# Generated by Django 4.1.7 on 2023-08-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='arquivo',
            field=models.ImageField(default=1, upload_to='imagens'),
            preserve_default=False,
        ),
    ]
