# Generated by Django 4.1.7 on 2023-08-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_midia_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='path',
        ),
    ]
